Elainebritodev/projeto-soul-viagens

src/app/app.module.ts
src/app/core/models/converter.ts
src/app/core/models/diario.ts
src/app/core/services/auth/auth.service.ts
src/app/core/services/dashboard/dashboard.service.ts
src/app/core/services/diarios/diarios.service.ts
src/app/core/services/upload/upload.service.ts
src/app/dashboard/components/week-posts/week-posts.component.ts
src/app/dashboard/dashboard.component.ts
src/app/diarios/components/diario-add/diario-add.component.ts
src/app/diarios/components/diario-detail/diario-detail.component.ts
src/app/diarios/components/diario-edit/diario-edit.component.ts
src/app/diarios/components/diario-list/diario-list.component.ts
src/app/diarios/diarios-routing.module.ts
src/app/diarios/diarios.module.ts
src/app/shared/components/loader/loader.component.html
src/app/shared/components/loader/loader.component.ts
src/app/shared/material.module.ts
src/app/shared/shared.module.ts
src/index.html

Limpeza do codigo

---

src/app/auth/auth-routing.module.ts
src/app/auth/auth.module.ts
src/app/auth/components/cadastro/cadastro.component.html
src/app/auth/components/login/login.component.html
src/app/auth/components/termos-de-privacidade/termos-de-privacidade.component.html
src/app/auth/components/termos-de-privacidade/termos-de-privacidade.component.scss
src/app/auth/components/termos-de-privacidade/termos-de-privacidade.component.spec.ts
src/app/auth/components/termos-de-privacidade/termos-de-privacidade.component.ts

Card Termos de Privacidade concluído

---

src/app/core/components/navbar/navbar.component.html
src/app/core/components/navbar/navbar.component.ts

adicionado botão para alterar cores da navbar

---

src/app/diarios/components/diario-add/diario-add.component.html
src/app/diarios/components/diario-add/diario-add.component.scss
src/app/diarios/components/diario-add/diario-add.component.ts

Mudança de icone e cor do check do upload

---

src/app/auth/auth-routing.module.ts
src/app/core/components/navbar/navbar.component.html
src/app/core/components/navbar/navbar.component.scss
src/app/core/components/navbar/navbar.component.ts

colocado link no logo

---

src/app/core/components/navbar/navbar.component.html

inclusão do email na navbar quando logado

---

src/app/auth/components/login/login.component.html
src/app/auth/components/login/login.component.scss
src/app/auth/components/login/login.component.spec.ts
src/app/auth/components/login/login.component.ts

Icon com função de ofuscar senha

CardOfuscar Senha

---

src/app/diarios/components/diario-list/diario-list.component.html
src/app/diarios/components/diario-list/diario-list.component.scss

Card de melhoria da página de detalhe - não finalizado

---

src/app/core/components/navbar/navbar.component.html

coreção da logo nav bar

---

.firebaserc
angular.json
src/app/auth/components/login/login.component.html
src/app/auth/components/login/login.component.ts
src/app/core/services/auth/auth.service.ts

Adicionado metodo de fazer login com facebook

---

src/app/diarios/components/diario-list/diario-list.component.html
src/app/diarios/components/diario-list/diario-list.component.scss

 Melhorias visuais dos cards de diário - Meus diários

---

src/app/auth/components/login/login.component.html
src/app/auth/components/login/login.component.scss
src/app/auth/components/login/login.component.ts

SenhaCorrigido

---

package-lock.json
package.json
src/app/auth/auth.module.ts
src/app/auth/components/cadastro/cadastro.component.html
src/app/auth/components/cadastro/cadastro.component.ts
src/app/auth/components/login/login.component.html
src/app/auth/components/login/login.component.ts

 Não sou um robô - captcha nos formulários de login e cadastro

---

src/app/app.component.html
src/app/auth/components/cadastro/cadastro.component.html
src/app/auth/components/login/login.component.html
src/app/core/components/footer/footer.component.html
src/app/core/components/footer/footer.component.scss
src/app/core/components/footer/footer.component.spec.ts
src/app/core/components/footer/footer.component.ts
src/app/core/core.module.ts

Footer para ser exibido em todas as páginas do app

---

src/app/auth/components/cadastro/cadastro.component.html

Implementação do Stepper

---

src/app/auth/components/login/login.component.html
src/app/auth/components/login/login.component.scss
src/app/auth/components/login/login.component.ts

Melhoria visual na página de login

---

src/app/auth/components/cadastro/cadastro.component.html
src/app/auth/components/cadastro/cadastro.component.scss
src/app/auth/components/cadastro/cadastro.component.ts

Melhoria visual na página de cadastro

---

package-lock.json
package.json
src/app/core/services/diarios/diarios.service.ts
src/app/diarios/components/diario-list/diario-list.component.html
src/app/diarios/components/diario-list/diario-list.component.scss
src/app/diarios/components/diario-list/diario-list.component.ts
src/app/diarios/diarios.module.ts

- Alterado o método getTdodosDiarios, para realizar busca ordenada por data, ();
- Alterado disposição dos diarios em diario-list-componente html e diario-list-componente scss;

Realizado paginacao e ordenacao

---

src/app/core/services/dashboard/dashboard.service.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts

Implementação Quantidade de Usuários Dashboard.

---

src/app/auth/components/login/login.component.html
src/app/auth/components/login/login.component.scss
src/app/auth/components/login/login.component.ts
src/app/core/components/footer/footer.component.html
src/app/core/components/navbar/navbar.component.html
src/app/core/components/navbar/navbar.component.ts
src/app/diarios/components/diario-detail/diario-detail.component.html
src/app/diarios/components/diario-detail/diario-detail.component.scss
src/app/diarios/components/diario-list/diario-list.component.html
src/styles.scss

limpeza de codigos e correçoes de bugs
